"""Add db models

Revision ID: 8859560509dc
Revises: 
Create Date: 2025-01-12 15:58:52.502922

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '8859560509dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_of_interest',
                    sa.Column('file_name', sa.String(length=100), nullable=False),
                    sa.Column('geometry', Geometry(from_text='ST_GeomFromEWKT', name='geometry', nullable=False),
                              nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('projects',
                    sa.Column('name', sa.String(length=32), nullable=False),
                    sa.Column('start_date', sa.Date(), nullable=False),
                    sa.Column('end_date', sa.Date(), nullable=False),
                    sa.Column('description', sa.String(length=300), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )


def downgrade() -> None:
    op.drop_table('projects')
    op.drop_index('idx_area_of_interest_geometry', table_name='area_of_interest', postgresql_using='gist')
    op.drop_table('area_of_interest')
